### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by vallard** [forslund/spotify-skill#165]
**Is your feature request related to a problem? Please describe.**
I want to run this plugin in a mycroft docker environment. 

**Describe the solution you'd like**
Thanks for the wonderful project, I would like to understand how I can modify where the credentials for spotify are accessed.  When I run the auth.py tool it saves the credentials in `~/.config/spotipy/token.json` and `~/.config/spotipy/auth`.  I'd like to change the app to find the credentials with  a CREDENTIALS_DIR variable or something. 

**Describe alternatives you've considered**
* I could not run it in docker. 
* I could mount the entire home directory, but this isn't my favorite idea. 

**Additional context**
I don't need any code to be modified, I'm happy if you just tell me how it could be done. I think I just modify the code in `spotify.py` and add an env variable to it.  Any guidance would be appreciated!

**Comment by forslund** [comment]
Hi, the XDG_CONFIG_DIRS variable can be used to shift it to a location of your choice but that would affect the rest of mycroft (which will start using the XDG paths as well), your idea of an env variable is a good idea!

In auth.py you can probably change [L21](https://github.com/forslund/spotify-skill/blob/20.08/auth.py#L21) to

```python
auth_dir = os.environ.get('SPOTIFY_SKILL_CREDS_DIR') or BaseDirectory.save_config_path('spotipy')
```

You need to `import os` at the top somewhere and do a similar change in spotify.py on [L69](https://github.com/forslund/spotify-skill/blob/20.08/spotify.py#L69) to match.

Would love a PR for that, otherwise I can probably get time to add it this weekend.

**Comment by vallard** [comment]
yeah, I can work on it next weekend. (not this one) Will send a PR. Thank you!

**Comment by forslund** [comment]
Hi @vallard, did you do any work on this already or should I tackle it?

**Comment by vallard** [comment]
I haven’t been able to get to it. All you!

**Comment by forslund** [comment]
The addition has been merged and readme has been updated with brief info. Closing this issue now.
