### ISSUE TITLE
Cannot play public playlists

### ISSUE THREAD

**Issue by BNolet** [forslund/spotify-skill#87]
Not sure if this is going to be implemented but for example if I say "Play beast mode by spotify" it won't work. Seems like there's no language processing for anything more than "play X"

**Comment by forslund** [comment]
public playlists has by design not been enabled, But there are more and more feature requests for this so we'll probably add some kind of support for it. Basically as a 3rd or 4th step look up when handling generic "play X" requests and secondly for specific playlist requests (after personal playlists)

**Comment by BNolet** [comment]
Alright, if you need to test later or get more feedback, I'll be watching this

**Comment by forslund** [comment]
I pushed a first pass at the public playlists to the `feature/playlists` branch.

`play the playlist PUBLIC PLAYLIST` should now work. feel free to give it a go.

**Comment by BNolet** [comment]
I'll be able to test this tonight and I'll let you know my findings 👌 thanks for working on this

**Comment by BNolet** [comment]
Works quite well! Thank you @forslund
